# netlify.toml — garde les chemins générés par adapter-netlify
[build]
  command = "npm run build"
  publish = ".svelte-kit/output/client"
  functions = ".netlify/functions"

# (optionnel) redirection propre si tu ajoutes un sous-dossier basepath un jour
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
